### ISSUE TITLE
Update Twitter Logo to "X"

### ISSUE THREAD

**Issue by Piyush-Goenka** [Vinit710/MEDAI#10]
Type: Enhancement

Priority: Medium

Description:
As Twitter has rebranded itself to "X," the current logo in the application is outdated and still displays the traditional bird logo. This issue is to update all instances of the Twitter logo to reflect the new "X" branding.

<img width="206" alt="Screenshot 2024-10-14 at 12 57 23 AM" src="https://github.com/user-attachments/assets/841fde30-4dd3-4781-8024-f2ec67fc9377">

**Comment by Piyush-Goenka** [comment]
Hey @dead-shadow-7 
Please assign this issue to me.

**Comment by Vinit710** [comment]
@Piyush-Goenka  yeah, It will good enhancement.
