### ISSUE TITLE
Social handle not linked

### ISSUE THREAD

**Issue by mayank-0789** [Vinit710/MEDAI#11]
The social handle for twitter and linkedin is not linked yet

#screenshot
<img width="1259" alt="Screenshot 2024-10-14 at 1 03 57 AM" src="https://github.com/user-attachments/assets/a979e49d-3ed1-46dc-b57d-2fddd1ba1b4e">

**Comment by mayank-0789** [comment]
Hey @Vinit710  please assign me this issue and please provide the links for the social handles of the MED.ai

**Comment by Vinit710** [comment]
We currently don't want to link socials, but appreciate the concern.
