### ISSUE TITLE
Can you assign me changing and enhancing the Ui for your page 

### ISSUE THREAD

**Issue by Priyanshuraj21030** [Vinit710/MEDAI#26]
Can you assign me changing and enhancing the Ui for your page Than i will try to enhance your page Ui from my side

**Comment by dead-shadow-7** [comment]
Sure! But could you clarify which part of the website's UI you want to work on?

**Comment by Priyanshuraj21030** [comment]
About section and contact section as well

**Comment by Priyanshuraj21030** [comment]
can you put the label as hacktoberfest in this issue if possible

**Comment by Priyanshuraj21030** [comment]
I am unable to pull request can you please give me access

**Comment by Priyanshuraj21030** [comment]
@dead-shadow-7

**Comment by dead-shadow-7** [comment]
Sure

**Comment by dead-shadow-7** [comment]
The changes are reviewed by @Vinit710

**Comment by Priyanshuraj21030** [comment]
> The changes are reviewed by @Vinit710

Okay I will let you know accordingly

**Comment by Priyanshuraj21030** [comment]
I have done and open the pr will you open this issue or I have to create new issue for that

**Comment by Priyanshuraj21030** [comment]
Okay
