### ISSUE TITLE
[BUG] The failure of chat history section in chat bot

### ISSUE THREAD

**Issue by Jils31** [Vinit710/MEDAI#28]
As talking with AI i found that the without any chat the chat history is still updating without doing anything and also it can be updated as user can edit the name of it and also should be able to remove a specific chat..

[Screencast from 2024-10-15 21-49-21.webm](https://github.com/user-attachments/assets/4efbda4d-f202-412b-8e35-424bffaa827a)

I can work on this issue , please assign this issue to me , Thanks!!

**Comment by Vinit710** [comment]
Yeah sure, the chat history updated when ever you refresh so make better by not updating regularly or storing empty chats.

**Comment by Vinit710** [comment]
Solved
