### ISSUE TITLE
Styling of the chatbot and booking form is not proper

### ISSUE THREAD

**Issue by Saachi30** [Vinit710/MEDAI#32]
# Layout Issues in MED.ai Chatbot Interface

## Description
We need to address several layout issues in MED.ai Chatbot interface, specifically focusing on the navbar, chatbot container, and booking form. The current layout is not optimal and needs to be improved for better user experience and visual consistency.

## Current Issues
1. Navbar: Spacing of tabs not proper
2. Chatbot Container: Layout and alignment is not proper, and not responsive
3. Booking Form: The booking form is not properly aligned and doesn't utilize the full width of the page effectively.

### Navbar
**Before:**
![image](https://github.com/user-attachments/assets/3a3371e3-91b5-4c6c-bb28-e412d01a21da)

**After:**
![image](https://github.com/user-attachments/assets/6fd9cf31-75d6-4219-899f-c95771bec023)

### Chatbot Container
**Before:**
![image](https://github.com/user-attachments/assets/1534fc86-c2e8-446e-ab1e-f91db8d60f17)

**After:**
![image](https://github.com/user-attachments/assets/e5e63aa8-f4c8-48ca-9fd1-d58a3a9330f1)

### Booking Form
**Before:**
![image](https://github.com/user-attachments/assets/43714fdb-4fbf-4066-875a-323d38d09ecd)

**After:**
![image](https://github.com/user-attachments/assets/31a06626-0d39-463f-b03f-8abc1bac13ef)

### Responsiveness
![image](https://github.com/user-attachments/assets/f277c2cc-8827-46dc-b738-35e90fac43c9)
![image](https://github.com/user-attachments/assets/9461ecc7-9717-40ae-9aab-045c87756a8e)
![image](https://github.com/user-attachments/assets/6d0198b0-1608-4311-a1b6-00f51c0af972)

## Technical Details
- Files to be modified:
  - `chatbot.html`
  - `index.html`

## Acceptance Criteria
- [x] Navbar is properly fixed and styled
- [x] Chatbot container layout is improved and functional
- [x] Booking form is positioned below the chatbot and spans the full width of the container
- [x] All elements are responsive and work well on various screen sizes
- [x] Design is consistent with the overall application theme

**I have already made the changes on my side, please assign this issue to me , so that i can make a pull request with all the changes**

**Comment by Vinit710** [comment]
Looks great, Raise the pr so i can review changes.
