### ISSUE TITLE
🌟: Adding a voice input feature for communicating with chatbot

### ISSUE THREAD

**Issue by Vinit710** [Vinit710/MEDAI#42]
### Title

A voice enabled communication system for the current chatbot

### Feature Aim

We want the users to communicate with chatbot through inputs and chatbot respond in audio as well.

### Changes

The changes will be required in chatbot.html page and the server.mjs file if you are using api's for communictaion.

### Full Name

N/A

**Comment by Vinit710** [comment]
If anyone can work on this, feel free to comment

**Comment by IngaleChinmay04** [comment]
Hi, I'd like to take on this issue and give it a try. Can you assign it to me?

**Comment by Vinit710** [comment]
@IngaleChinmay04 Yeah sure
You can give it a try.
